kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-nodeport
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: eck-elasticsearch
  type: NodePort
  ports:
    - port: 9200
      name: rest
      nodePort: 30090
    - port: 9300
      name: inter-node
      nodePort: 30091